[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "opytimal"
version = "0.9.9.1"
authors = [
  { name="Natanael Quintino", email="natanaelquintino@gmail.com" },
]
description = "Optimal control PDE-based solver"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/NaelQuin/opytimal"
"Bug Tracker" = "https://github.com/NaelQuin/opytimal/issues"